{{- if and .Values.ingress.enabled .Values.certificates.enabled }}
{{- range .Values.certificates.certs }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.global.namespace | default $.Release.Namespace }}
  labels:
    {{- include "nlp-ingress.labels" $ | nindent 4 }}
spec:
  secretName: {{ .secretName }}
  issuerRef:
    name: {{ .issuerRef.name }}
    kind: {{ .issuerRef.kind | default "ClusterIssuer" }}
  dnsNames:
    {{- range .dnsNames }}
    - {{ . }}
    {{- end }}
  {{- if .duration }}
  duration: {{ .duration }}
  {{- end }}
  {{- if .renewBefore }}
  renewBefore: {{ .renewBefore }}
  {{- end }}
---
{{- end }}
{{- end }}