{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nlp-ingress.fullname" . }}-netpol
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "nlp-ingress.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: nginx-ingress
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Autoriser le trafic HTTPS/HTTP entrant
    - from: []
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
  egress:
    # Autoriser l'accès aux services backend
    {{- range .Values.networkPolicy.allowedServices }}
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .name }}
      ports:
        - protocol: TCP
          port: {{ .port }}
    {{- end }}
    # DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}