{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mistral-server.fullname" . }}-pvc
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  annotations:
    {{- toYaml .Values.persistence.annotations | nindent 4 }}
spec:
  accessModes: 
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
{{- end }}
