apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "torchserve.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "torchserve.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "torchserve.name" . }}
    spec:
      containers:
        - name: torchserve
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: model-store
              mountPath: {{ .Values.modelStore.mountPath }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
      volumes:
        - name: model-store
          persistentVolumeClaim:
            claimName: {{ .Values.modelStore.pvcName }}