replicaCount: 2

image:
  repository: your-docker-registry/your-torchserve-image
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

modelStore:
  mountPath: /home/model-server/model-store
  pvcName: torchserve-models-pvc
