apiVersion: v2
name: nlp-ingress
description: A Helm chart for NLP Platform Ingress Configuration
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - ingress
  - nginx
  - nlp
  - api-gateway

dependencies:
  - name: ingress-nginx
    version: "4.7.1"
    repository: https://kubernetes.github.io/ingress-nginx
    condition: nginx.enabled

home: https://github.com/cnaas/nlp-platform
sources:
  - https://github.com/cnaas/nlp-platform

maintainers:
  - name: Ludovic Marco
    email: contact@cnaas.link

