{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mistral-server.fullname" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mistral-server
  endpoints:
    - port: http
      path: {{ .Values.monitoring.serviceMonitor.path }}
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end }}
