apiVersion: v2
name: mistral-server
description: |
  Helm chart pour déployer Mistral Inference Server
  (API de génération de texte) sur Kubernetes avec support GPU, ingress et cert-manager.
type: application
version: 0.1.0            # version du chart
appVersion: "0.3.0"       # version de l’app (correspond à l’image Mistral utilisée)

maintainers:
  - name: Ludovic Marco Palamède
    email: ton.email@example.com

keywords:
  - mistral
  - llm
  - inference
  - nlp
  - torchserve
  - ai

home: https://mistral.ai
sources:
  - https://github.com/mistralai/mistral-src
  - https://gitlab.com/tonrepo/nlp-orchestrator

icon: https://mistral.ai/wp-content/uploads/2023/09/mistral-logo.png
