{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nlp-api.fullname" . }}-config
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "nlp-api.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}