{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nlp-api.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "nlp-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}